export const companyMap = {
  APPLE: 'NASDAQ:AAPL',
  MICROSOFT: 'NASDAQ:MSFT',
  GOOGLE: 'NASDAQ:GOOGL',
  AMAZON: 'NASDAQ:AMZN',
  NVIDIA: 'NASDAQ:NVDA',
  META: 'NASDAQ:META',
  TESLA: 'NASDAQ:TSLA',
  RELIANCE: 'NSE:RELIANCE',
  TCS: 'NSE:TCS',
  INFY: 'NSE:INFY',
  HDFCBANK: 'NSE:HDFCBANK',
  SBI: 'NSE:SBIN',
};
